### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by lfarah** [KentaKudo/Smeargle#5]
I created this [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) and you're more than welcome on using it on **Smeargle**.

Let me know if you need any help! 😉

**Comment by KentaKudo** [comment]
@lfarah 
Looks great!
I've wanted a nice template like this.

Thanks!!

**Comment by lfarah** [comment]
Awesome. Happy to help! 😃
